// Static list of avatar images under public/assets/trainers.
// Regenerate with: ls public/assets/trainers | awk '{print "  '\''/assets/trainers/" $0 "'\'',"}'
export const AVATAR_IMAGES = [
  '/assets/trainers/ace trainer.png',
  '/assets/trainers/alder.png',
  '/assets/trainers/aroma-lady.png',
  '/assets/trainers/artist.png',
  '/assets/trainers/backpacker.png',
  '/assets/trainers/barry.png',
  '/assets/trainers/bianca.png',
  '/assets/trainers/black-belt.png',
  '/assets/trainers/brycen.png',
  '/assets/trainers/bug-catcher.png',
  '/assets/trainers/bunny.png',
  '/assets/trainers/caitlin.png',
  '/assets/trainers/candice.png',
  '/assets/trainers/cheryl.png',
  '/assets/trainers/clown.png',
  '/assets/trainers/collector.png',
  '/assets/trainers/colress.png',
  '/assets/trainers/cynthia.png',
  '/assets/trainers/cyrus.png',
  '/assets/trainers/dawn.png',
  '/assets/trainers/elder.png',
  '/assets/trainers/fisherman.png',
  '/assets/trainers/gentleman.png',
  '/assets/trainers/ghetsis.png',
  '/assets/trainers/iris.png',
  '/assets/trainers/janine.png',
  '/assets/trainers/lance.png',
  '/assets/trainers/lucas.png',
  '/assets/trainers/N.png',
  '/assets/trainers/nate.png',
  '/assets/trainers/pokemon-center-lady.png',
  '/assets/trainers/riley.png',
  '/assets/trainers/roxie.png',
  '/assets/trainers/scientist.png',
  '/assets/trainers/skyla.png',
  '/assets/trainers/steven.png',
  '/assets/trainers/volkner.png',
];
